name: Unit Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    timeout-minutes: 10

    steps:
      - name: Install `xvfb`
        run: sudo apt install xvfb

      - name: Export DISPLAY var
        run: export DISPLAY=':99.0' & xvfb-run x.org_application_binary

      - name: Setup Screen
        run: "Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Requirements
        run: python -m pip install -r requirements.txt & python -m pip install -r test_requirements.txt

      - name: Execute Tests
        run: pytest -v tests/ --cov=mats
