name: Unit Tests, Python 3.8
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Requirements
        run: python -m pip install -r requirements.txt & python -m pip install -r test_requirements.txt

      - name: Execute Tests
        run: pytest -v tests/
